### PR TITLE
Updating various parts in globe.js and starting with prettier.js

### PR DESCRIPTION
**Pull request by rscircus**

### CODE REVIEW

**Comment by mrdoob** [comment]
Is this only formatting changes?

**Comment by rscircus** [comment]
Yes, it's prettie with tab-width of 2 spaces and otherwise defaults. I'm going to clean up the global.js a bit and started with this. :)

**Comment by rscircus** [comment]
Meanwhile I also started to extend the `global.js` already a bit, too... you can have a look at the state of things here: https://rscircus.github.io/pages/climate_anomaly/

**Comment by mrdoob** [comment]
I don't think you're going to have much success reformatting code in a project that has not been updated in 4 years.

**Comment by rscircus** [comment]
Hm, it still works quite nicely for my purpose. I started to add touch without the Swipe controls.js and the likes. Alright. I'll stay in my fork then.

**Comment by rscircus** [comment]
OK, a few days later, I understand your comment a bit better. I'm migrating to the most recent `three.js` right now... thanks for this (`three.js`) project. First did a move to integrate pinch-to-zoom and now wanted to dabble with VR. It's fun. :)

**Pull request closed without merging**
